language: go
go:
  - 1.9
sudo: false
before_script:
  - go vet ./...
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username reflog --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/  